services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data
      - ./data:/docker-entrypoint-initdb.d


volumes:
  mongodb_data: